### ISSUE TITLE
Login with encrypted private key fails

### ISSUE THREAD

**Issue by GuyXY** [masaeedu/win-sshfs#4]
When I try to connect to my ssh server with an encrypted private key, it fails to connect with the following error:
```
Unbehandelte Ausnahme: Renci.SshNet.Common.SshPassPhraseNullOrEmptyException: Private key is encrypted but passphrase is empty.
   bei Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, String passPhrase)
   bei Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)
   bei SSHFS.CLI.Program.<>c.<PrivateKeyConnectionInfo>b__2_0(String k) in C:\projects\win-sshfs\Sshfs\SSHFS.CLI\Program.cs:Zeile 99.
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei SSHFS.CLI.Program.PrivateKeyConnectionInfo(Options options) in C:\projects\win-sshfs\Sshfs\SSHFS.CLI\Program.cs:Zeile 97.
   bei SSHFS.CLI.Program.GetAuthMechanisms(Options options) in C:\projects\win-sshfs\Sshfs\SSHFS.CLI\Program.cs:Zeile 79.
   bei SSHFS.CLI.Program.Main(String[] args) in C:\projects\win-sshfs\Sshfs\SSHFS.CLI\Program.cs:Zeile 61.
```
After that I get this classical error:
![winsshfscli](https://user-images.githubusercontent.com/5495060/33522126-0ea20c2e-d7e5-11e7-8914-88c142dc4109.PNG)

From the error message, it seems like I don't supply the required "-x/--password" parameter but that is not the case either.

**Comment by masaeedu** [comment]
@GuyXY The `-x` password parameter is for password/keyboard-interactive login, it isn't used for decrypting private keys.

I could just add another parameter to accept the private key passphrase, but having a password in a CLI param is a security risk. For my use case, the machines I'm ssh-ing into are ephemeral and just have `p@ssw0rd` as the password, so I'm not losing anything if that password gets pwned. 

However in general, if people start putting important information like their private key passphrase in the command line invocation, they need to be aware that said passphrase is accessible to any process on the box that does the Windows equivalent of `ps` .

I think I am going to remove the `-x` command line argument and change things so that a passphrase/password is sent through stdin if needed. If people are starting to use the tool with sensitive info I also need to handle the password more carefully. At the very least I need to add a strong disclaimer in the README about the lax state of security at the moment.

**Comment by Schroedi** [comment]
I had the same problem. For a quick workaround, I always read the key's passphrase: https://github.com/Schroedi/win-sshfs/tree/priv_key_pw
A way to check if a passphrase is required would be good.

**Comment by masaeedu** [comment]
I looked at the code again, and this is actually already supported in the command line options. It's undocumented, but the `-k` option doesn't just take a path to a private key file; you can add two spaces after the key file path and enter the passphrase, i.e. `-k <path to private key>  <passphrase>`.

I'm not really 100% sure what I was smoking when I wrote that stuff, the way it's implemented prevents whitespace in the key file path or passphrase (#7), but there you go. You can use that in the interim until I change this stuff to use an input stream (probably by the end of the week).

**Comment by h4de5** [comment]
is there any change you can use keys from pageant? like the winsshfs had previously?
this way we could use encrypted private keys and not expose the password/passphrase in the command line.

**Comment by masaeedu** [comment]
This should be fixed now. It's a breaking change, so you can no longer do `-x <yourpass>`. Instead the `-x` flag tells the program to ask for a password over stdin.

If you specify private keys, it will demand a passphrase for each private key file you specify, and if no private keys are specified, it will instead ask for a password to use for direct username/password authentication.

**Comment by masaeedu** [comment]
With #19 you can also do `echo "mypass" | sshfs.cli.exe ... -x`.
